version: '3'

services:
  go-proxy-bingai:
    image: zklcdc/go-proxy-bingai
    container_name: go-proxy-bingai
    restart: always
    ports:
      - 8080:8080
    environment:
      - BYPASS_SERVER=https://bypass.zklcdc.xyz
      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080
      # - Go_Proxy_BingAI_USER_TOKEN_1=xxx
      # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
      # - USER_KievRPSSecAuth=xxx
      # - USER_RwBf=xxx
      # - USER_MUID=xxx
      # - APIKEY=sk-xxx
